# Generated by Django 3.2.9 on 2021-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='r2.jpeg', upload_to='blog/'),
        ),
    ]
